name: zdm_crawler

on:
  #将下面两行代码取消注释
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn package
        cp ./target/zdm-0.0.1.jar ./zdm.jar
    - name: main logic
      env:
        #爬取数据时的最大翻页数量
        maxPageSize: 20
        # 点值的数量>minVoted,才会被推送,填0为都推送
        minVoted: 10
        # 评论的数量>minComments,才会被推送,填0为都推送
        minComments: 2
        # 优惠信息数量>MIN_PUSH_SIZE就会发邮件,否则积累到下一次触发任务再决定是否推送. 不建议填太小的数字,避免邮件太多了
        MIN_PUSH_SIZE: 20
        # 邮箱的smtp服务器地址(示例给出的是qq邮箱的配置,非qq邮箱需要进行修改)
        emailHost: smtp.qq.com
        # 邮箱smtp服务端口
        emailPort: 465
        # 接收优惠信息的邮箱 为空代表不进行邮箱推送
        emailAccount: ${{secrets.emailAccount}}
        # 接收优惠信息的邮箱的授权码 为空代表不进行邮箱推送
        emailPassword: ${{secrets.emailPassword}}
        
        # WxPusher极简推送模式的spt 为空代表不进行Wx推送
        # This is likely your WxPusher UID or a user-specific topic token
        spt: ${{secrets.SPT}}
        
        # ADDED: WxPusher Application Token
        # You need to create a GitHub Secret named WX_PUSHER_APP_TOKEN (or similar)
        # and store your WxPusher AppToken value in it.
        # The Java application needs this to authenticate with WxPusher.
        # Common environment variable names for this are WX_PUSHER_APP_TOKEN, wxPusherAppToken, or appToken.
        # Check your Java application's documentation or code if this specific name doesn't work.
        WX_PUSHER_APP_TOKEN: ${{secrets.WX_PUSHER_APP_TOKEN}} # Ensure this secret exists in your repo

        # true:下载阶段打印出详细信息(待推送的优惠信息列表,过滤时使用的黑白词),因文本量比较大,在调通项目后可以改为false
        detail: false
      run: java -jar zdm.jar
    #保存已推送和暂未推送的优惠信息
    - name: git add files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add database.db
    - name: commit & push
      uses: actions-go/push@master # Consider using a more maintained action like stefanzweifel/git-auto-commit-action
      with:
        author-email: 'actions@github.com'
        author-name: 'GitHub Actions'
        commit-message: 'update articles'
        token: ${{secrets.GIT_TOKEN}}
